runtime: nodejs18

env_variables:
  NODE_ENV: production
  SMTP_PORT: 2525
  SMTP_HOST: 0.0.0.0
  GOOGLE_CLOUD_API_KEY: AIzaSyBVNhxZLW6nR5r5H02KhF9bJ_NeTamCjy8

automatic_scaling:
  min_instances: 1
  max_instances: 10

network:
  forwarded_ports:
    - 2525

resources:
  cpu: 1
  memory_gb: 1