steps:
  # Build Docker image (TypeScript compilation happens inside Docker)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'smtp-server',
      '--image', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID',
      '--region', 'us-central1',
      '--port', '2525',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'SMTP_HOST=0.0.0.0',
      '--set-env-vars', 'SMTP_PORT=2525'
    ]

images:
  - 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY