steps:
  # Build TypeScript
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
  
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID', '.']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'smtp-server',
      '--image', 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID',
      '--region', 'us-central1',
      '--port', '2525',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10'
    ]

images:
  - 'gcr.io/$PROJECT_ID/smtp-server:$BUILD_ID'